# Generated by Django 4.1.5 on 2023-02-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(default='D:\\BROCAMB PROJECTS\\WEEK 8\\PROJECTS\\sample ignite\\sampleignite\\images\\gbook1.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
