# Generated by Django 4.1.5 on 2023-02-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_picture_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
