# Generated by Django 4.1.5 on 2023-02-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, default='D:\\BROCAMB PROJECTS\\WEEK 8\\PROJECTS\\sample ignite\\sampleignite\\images\\gbook1.jpg', null=True, upload_to='media/'),
        ),
    ]
