# Generated by Django 4.1.5 on 2023-02-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_category_products_p_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
