# Generated by Django 4.1.5 on 2023-02-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_userdetails_u_active_alter_products_p_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(upload_to='newimg'),
        ),
    ]
